### INPUT

#ckpt_path     : /home/npearl/Documents/PycharmProjects/nan/out/sanity_check__NAN/model_005000.pth  # TODO 0 Naama
distributed   : False

## dataset
eval_dataset : llff_test
eval_scenes  : fern

### TESTING
chunk_size    : 2048
render_stride : 1

## ADDITIONAL
same          : True
num_source_views : 8

## EVAL
# eval_images : True # TODO
# eval_rays : True # TODO
# rerun : True # TODO

process_output : True

local_rank : 0
