### INPUT

# TODO Naama create default evaluation config
ckpt_path     : D:\Naama\Documents\Projects\nan\out\unproc_gamma_wl____full__pre__expand_rgb_3_3_3__blend_src__views_attn__noise_feat__l1\model_255000.pth
distributed   : False

## dataset
eval_dataset : llff_test
eval_scenes  : fern

### TESTING
chunk_size    : 2048
render_stride : 1

## ADDITIONAL
same          : True
num_source_views : 8

process_output : True